default:
  tags:
    - CREMI
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

build-nom:
  stage: build
  script :
    - pip install coverage

test-point:
  stage: test
  script :
    - python3 -m unittest -v VideoTracker/TestsUnitaires/TestPoint.py

coverage-point:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run -m pytest VideoTracker/TestsUnitaires/TestPoint.py
    - coverage report -m

