default:
  tags:
    - CREMI
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

build-nom:
  stage: build
  script :
    - pip install coverage

test-graph:
  stage: test
  script :
    - python3 -m unittest -v VideoTracker/TestsUnitaires/TestGraph.py

test-filerepo:
  stage: test
  script :
    - python3 -m unittest -v VideoTracker/TestsUnitaires/TestFileRepo.py

test-point:
  stage: test
  script :
    - python3 -m unittest -v VideoTracker/TestsUnitaires/TestPoint.py

coverage-graph:
    stage: coverage
    script :
      - coverage run -m unittest
      - coverage run --source=Graph -m pytest VideoTracker/TestsUnitaires/TestGraph.py
      - coverage report -m

coverage-filerepo:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run --source=FileRepo -m pytest VideoTracker/TestsUnitaires/TestFileRepo.py
    - coverage report -m

coverage-point:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run --source=Point -m pytest VideoTracker/TestsUnitaires/TestPoint.py
    - coverage report -m

